{{- with index .Values "cluster-configs" "secrets" "github-rsa" }}
{{- if index . "id_rsa" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "github-ssh" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  id_rsa: {{ index $.Values "cluster-configs" "secrets" "github-ssh" "id_rsa" | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
